name: CI Pipeline (Advanced Image Match)

on:
  push:
    branches:
      - main
    paths:
      - 'MLProject/**'

permissions:
  contents: write  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run actions/checkout@v3
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Check Env
      run: |
        python --version
        pip --version
        ls -R

    - name: Install dependencies
      run: |
        pip install mlflow==2.19.0 dagshub pandas scikit-learn matplotlib seaborn

    - name: Run mlflow project
      env:
        MLFLOW_TRACKING_USERNAME: AtthalaricNero
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        MLFLOW_TRACKING_URI: https://dagshub.com/AtthalaricNero/Proyek_ML_Dicoding.mlflow
      run: |
        cd MLProject
        mlflow run . --env-manager=local

    - name: Get latest MLflow run_id
      run: |
        echo "Run ID:"
        cat MLProject/run_id.txt

    - name: Commit and Push run_id to GitHub
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        git add MLProject/run_id.txt
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update run_id.txt from CI [skip ci]"
          git push
        fi

    - name: Install Python dependencies
      run: |
        echo "Dependencies already installed to prevent runtime error."
        pip install pandas scikit-learn matplotlib seaborn

    - name: Build Docker Model
      env:
        MLFLOW_TRACKING_USERNAME: AtthalaricNero
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        MLFLOW_TRACKING_URI: https://dagshub.com/AtthalaricNero/Proyek_ML_Dicoding.mlflow
      run: |
        RUN_ID=$(cat MLProject/run_id.txt)
        
        mlflow models build-docker \
          --model-uri "runs:/$RUN_ID/model_final" \
          --name "local-telco-model"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker Image
      run: |
        docker tag local-telco-model ${{ secrets.DOCKER_USERNAME }}/telco-churn-model:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/telco-churn-model:latest